# Known processes that negatively impact FPS
FPS_KILLER_PROCESSES = {
    "discord.exe": "Discord uses GPU acceleration for UI rendering and can cause frame time spikes. Disable hardware acceleration in Discord settings.",
    "obs64.exe": "OBS Studio (64-bit) consumes significant CPU/GPU for encoding even when not actively recording/streaming.",
    "obs32.exe": "OBS Studio (32-bit) consumes significant CPU/GPU for encoding even when not actively recording/streaming.",
    "msmpeng.exe": "Windows Defender antivirus real-time scanning can cause stutters during game load and asset streaming.",
    "SearchIndexer.exe": "Windows Search Indexer performs disk I/O and CPU work in background. Can cause stutters especially on HDDs.",
    "OneDrive.exe": "OneDrive cloud sync performs continuous disk I/O and network activity. Pause syncing while gaming.",
    "googledrivefs.exe": "Google Drive sync performs continuous disk I/O and network activity. Pause syncing while gaming.",
    "Dropbox.exe": "Dropbox sync performs continuous disk I/O and network activity. Pause syncing while gaming.",
    "iCUE.exe": "Corsair iCUE RGB software polls hardware sensors frequently and can cause CPU usage spikes.",
    "RazerSynapse.exe": "Razer Synapse RGB/peripheral management software has known performance overhead and can cause stutters.",
    "LGHUBUpdaterService.exe": "Logitech G HUB updater service runs background processes. Can cause periodic CPU spikes.",
    "nvcontainer.exe": "NVIDIA container for GeForce Experience overlay. Disable in-game overlay in GFE settings if not needed.",
    "GfExperienceService.exe": "GeForce Experience background service. Can be disabled if you manage drivers manually.",
    "Wallpaper32.exe": "Wallpaper Engine (32-bit) renders animated wallpapers continuously, consuming GPU resources.",
    "Wallpaper64.exe": "Wallpaper Engine (64-bit) renders animated wallpapers continuously, consuming GPU resources.",
    "Rainmeter.exe": "Rainmeter desktop customization tool renders UI elements continuously, using CPU and GPU.",
    "flux.exe": "f.lux color temperature adjustment software. Can interfere with HDR and full-screen exclusive mode.",
    "Teams.exe": "Microsoft Teams runs background processes including video decode, updates, and notifications.",
    "chrome.exe": "Google Chrome with hardware acceleration uses GPU resources. Close browser tabs while gaming.",
    "firefox.exe": "Mozilla Firefox uses GPU for rendering. Close browser while gaming for best performance.",
    "EpicGamesLauncher.exe": "Epic Games Launcher runs background services including crash reporter and update checks.",
    "steam.exe": "Steam client with web browser and overlay active. Disable Steam overlay for maximum performance.",
    "EADesktop.exe": "EA Desktop app runs background services and telemetry processes.",
    "XboxApp.exe": "Xbox app runs background services including Game Bar and capture features.",
    "OriginWebHelperService.exe": "EA Origin/App web helper service runs background processes and updates.",
    "SteamWebHelper.exe": "Steam web browser helper process. Runs when Steam overlay browser is active.",
    "NahimicService.exe": "Nahimic audio enhancement service (common with MSI motherboards) can cause audio driver conflicts and CPU overhead.",
    "AdobeUpdateService.exe": "Adobe update service performs background checks and downloads. Can spike CPU/disk.",
    "msiafterburner.exe": "MSI Afterburner is generally low overhead but can cause issues with certain games and anti-cheat.",
    "rtss.exe": "RivaTuner Statistics Server (RTSS) injects into game processes for OSD. Can conflict with some games.",
    "audiodg.exe": "Windows Audio Device Graph - if high CPU, indicates audio enhancement issues. Disable audio enhancements.",
    "igfxEM.exe": "Intel HD Graphics Event Monitor. Unnecessary on systems with dedicated GPU only.",
    "igfxHK.exe": "Intel HD Graphics HotKey driver. Unnecessary on systems with dedicated GPU only.",
    "igfxTray.exe": "Intel HD Graphics tray icon. Unnecessary on systems with dedicated GPU only.",
    "SynTPEnh.exe": "Synaptics touchpad driver enhancement process. Low overhead but adds to process count.",
    "Speccy.exe": "Speccy hardware monitoring tool polls sensors frequently, adding CPU overhead.",
    "HWiNFO64.exe": "HWiNFO sensor monitoring polls hardware frequently. Can cause stutters in some games.",
    "CPUID_HWMonitor.exe": "CPU-Z HW Monitor polls hardware sensors frequently, adding small CPU overhead.",
}

# Known problematic Windows services
PROBLEMATIC_SERVICES = {
    "DiagTrack": "Windows Telemetry/Diagnostics Tracking Service - sends diagnostic data to Microsoft, uses CPU and network.",
    "dmwappushservice": "Device Management WAP Push Service - telemetry related, typically safe to disable.",
    "SysMain": "Superfetch/SysMain - preloads apps into RAM. Can cause HDD thrashing. Disable on systems with SSDs only.",
    "WSearch": "Windows Search Indexing Service - constant background disk I/O. Disable if you don't use Windows Search.",
    "Spooler": "Print Spooler - unnecessary if you don't print. Common attack vector, disable if not needed.",
    "Fax": "Fax service - rarely needed on modern PCs, wastes resources.",
    "RemoteRegistry": "Remote Registry service - security risk and unnecessary for gaming.",
    "TabletInputService": "Touch keyboard and handwriting panel - unnecessary on desktop PCs.",
    "WbioSrvc": "Windows Biometric Service - only needed if using fingerprint/face login.",
    "XblAuthManager": "Xbox Live Auth Manager - part of Xbox integration. Can be disabled if not using Xbox features.",
    "XblGameSave": "Xbox Live Game Save - syncs game saves to Xbox Live. Disable if not using Xbox.",
    "XboxNetApiSvc": "Xbox Live Networking Service - Xbox network features. Disable if not using Xbox.",
    "wuauserv": "Windows Update - can trigger downloads/installs at bad times. Check if actively updating.",
    "TrustedInstaller": "Windows Module Installer - runs during Windows updates. High disk/CPU usage indicates active update.",
    "BITS": "Background Intelligent Transfer Service - used for Windows Update downloads in background.",
    "NahimicSvc": "Nahimic Audio Service - audio enhancement that can cause conflicts. Disable if having audio issues.",
    "RzActionSvc": "Razer Action Service - part of Razer Synapse. High overhead RGB management.",
    "CorsairGamingAudioConfig": "Corsair Audio Configuration - part of iCUE suite.",
}

# Known driver versions with issues
KNOWN_BAD_DRIVER_VERSIONS = {
    "nvidia_notes": "NVIDIA drivers 526.x had memory leak issues in DX12. Drivers 531.x+ are generally stable.",
    "nvidia_526": "NVIDIA 526.x series - known memory leak in DirectX 12 applications.",
    "nvidia_512": "NVIDIA 512.x series - known issues with some anti-cheat systems.",
    "amd_notes": "AMD drivers 22.x had stuttering issues in some titles. 23.x+ generally improved.",
    "intel_arc_notes": "Intel Arc drivers pre-31.0 had significant performance and compatibility issues.",
    "realtek_audio": "Older Realtek audio drivers (pre-6.0.9) can cause audiodg.exe high CPU.",
    "killer_network": "Intel Killer network drivers have had bloatware/performance issues. Consider switching to standard Intel drivers.",
}

# Processes that are known overlays (inject into game process)
OVERLAY_PROCESSES = [
    "GameBar.exe",
    "GameBarFTServer.exe",
    "XboxApp.exe",
    "GfExperienceService.exe",
    "nvcontainer.exe",
    "OVRServer_x64.exe",
    "vrserver.exe",
    "SteamWebHelper.exe",
    "EpicWebHelper.exe",
    "discord.exe",
    "obs64.exe",
    "obs32.exe",
    "rtss.exe",
    "afterburner.exe",
    "msiafterburner.exe",
    "fraps.exe",
    "bandicam.exe",
    "playstv_launcher.exe",
    "Plays.exe",
    "medal.exe",
    "overwolf.exe",
    "OverwolfBrowser.exe",
]
